context:
  version: 3.11.0a4

package:
  name: mypython
  version: '{{ version }}'


# source:

source:
  git_url: https://github.com/python/cpython
  git_rev: main


# - url: https://github.com/python/cpython/archive/refs/tags/v{{ version }}.tar.gz

build:
  number: 0
  detect_binary_files_with_prefix: true
  # run_exports:
  #   - "{{ pin_subpackage('python', max_pin='x.x') }}"

    
requirements:
  build:
    - sel(unix):          make           
    - sel(emscripten):    mypython
    - sel(emscripten):    binutils
  # host:
  #   - sel(not win and not emscripten): readline
  #   - sel(not win and not emscripten): ncurses 
  # run:
  #   - sel(not win and not emscripten): readline
  #   - sel(not win and not emscripten): ncurses 


about:
  home: todo
  summary: todo
  license: todo
  license_file: todo

extra:
  recipe-maintainers:
    - DerThorsten