context:
  version: 1.2.0

package:
  name: toy_lib
  version: '{{ version }}'

source:
  # path: /home/derthorsten/src/toy_lib/
  url: https://github.com/DerThorsten/toy_lib/archive/refs/tags/{{ version }}.tar.gz
  # sha256: d042a2c2ccdef668ccac15b675d8c1bdfa61d86e2db0d22afff0ce92a6d6e8ec

build:
  number: 1
  # run_exports:
  #   - '{{ pin_subpackage("toy_lib", max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja



about:
  home: https://github.com/DerThorsten/toy_lib
  license: MIT
  license_family: MIT
  # license_file: LICENSE
  summary: toy_lib is a toy lib
  doc_url: https://github.com/DerThorsten/toy_lib
  dev_url: https://github.com/DerThorsten/toy_lib

extra:
  recipe-maintainers:
    - DerThorsten

