context:
  version: 2.1.2

package:
  name: CLI11
  version: '{{ version }}'

source:
  url: https://github.com/CLIUtils/CLI11/archive/refs/tags/v{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja

about:
  home: https://github.com/CLIUtils/CLI11
  license: Custom
  license_family: Custom
  license_file: LICENSE
  summary: CLI11
  doc_url: https://github.com/CLIUtils/CLI11
  dev_url: https://github.com/CLIUtils/CLI11

extra:
  recipe-maintainers:
    - DerThorsten

