context:
  name: emscripten_emscripten-32
  version: 0.23.10

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 0

# requirements:


#   run:
#     - emscripten
#     - llvm 12.*


about:
  home: emscripten
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: emscripten
  description: emscripten
  doc_url: emscripten
  dev_url: emscripten

extra:
  recipe-maintainers:
    - DerThorsten
