context:
  version: 1.2.0

package:
  name: toy_bin
  version: '{{ version }}'

source:
  url: https://github.com/DerThorsten/toy_bin/archive/refs/tags/{{ version }}.tar.gz
  # path: /home/derthorsten/src/toy_bin/
  # sha256: 70d9cbda62fcf7d205b72fc499c9ec82082b9cbffa8ffb84be86223e7b3a71d0

build:
  number: 0
  # run_exports:
  #   - '{{ pin_subpackage("toy_bin", max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja

  run:
    - toy_lib
  host:
    - toy_lib



about:
  home: https://github.com/DerThorsten/toy_bin
  license: MIT
  license_family: MIT
  # license_file: LICENSE
  summary: toy_bin is a toy lib
  doc_url: https://github.com/DerThorsten/toy_bin/
  dev_url: https://github.com/DerThorsten/toy_bin

extra:
  recipe-maintainers:
    - DerThorsten

